- name: "Debian | St"
  block:
    - name: "Debian | St | Create {{ suckless_common_build_home }}/{{ role_name }}" # noqa: name[template]
      ansible.builtin.file:
        name: "{{ suckless_common_build_home }}/{{ role_name }}"
        state: directory
        mode: "0700"
        owner: "{{ suckless_common_build_user }}"
        group: "{{ suckless_common_build_group }}"

    - name: "Debian | St | Dependencies"
      vars:
        pkg_state: present
        pkg_names:
          - sudo
          - patch
          - git
          - make
          - libx11-6
          - libx11-xcb1
          - libx11-dev
          - libxft-dev
          - libxinerama-dev
          - libgcr-3-dev
          - libwebkit2gtk-4.0-dev
          - gcc
          - acl
          - libglib2.0-dev
      ansible.builtin.include_role:
        name: ruupert.helpers.pkg

    - name: "Debian | St | Compile"
      vars:
        suckless_build_name: "{{ role_name }}"
        suckless_build_repo: "{{ st_repo }}"
        suckless_build_branch: "{{ st_branch }}"
        suckless_build_patches: "{{ st_patches }}"
        suckless_build_patch: "{{ st_patch }}"
        suckless_build_path: "{{ suckless_common_build_home }}/{{ role_name }}/repo"
        suckless_build_user: "{{ suckless_common_build_user }}"
        suckless_build_group: "{{ suckless_common_build_group }}"
        suckless_build_recompile: "{{ st_recompile }}"
      ansible.builtin.include_tasks:
        file: ../../common/tasks/Compile.yml

  rescue:
    - name: "Debian | St | Fail"
      ansible.builtin.debug:
        msg: "Fail"
      changed_when: true
      # notify:
      #   - send failed message
