namespace: ruupert
name: suckless
version: 1.0.2
readme: README.md
authors:
  - Raul Becker
description: Clones, patches, compiles and installs x11 suckless progs.
license:
  - GPL-2.0-or-later
tags: ['application', 'dwm', 'dmenu', 'st', 'dwmstatus', 'slstatus', 'surf', 'tabbed', 'wmname', 'slock']
dependencies:
  community.general: '>=1.5.4'
  ansible.posix: '>=8.6.0'
repository: http://github.com/ruupert/suckless
documentation: http://github.com/ruupert/suckless
homepage: http://github.com/ruupert/suckless
issues: http://github.com/ruupert/suckless/issues
build_ignore:
  - .venv
  - .vagrant
  - .gitignore
  - playbook.yml
  - ansible.cfg
  - Vagrantfile
  - setup.sh
  - test.sh
  - requirements.yml
  - .ansible-lint
  - '*.tar.gz'
  - .yamllint
  - .editorconfig
