---
- name: "Debian dwm"
  hosts: "all:!localhost"
  become: true
  roles:
    - { role: dwm }
    - { role: dwm, vars: { act: 'recompile' } }
    - { role: dwm, vars: { rerun: 'true'} }
    - { role: dmenu }
    - { role: dmenu, vars: { act: 'recompile' } }
    - { role: dmenu, vars: { rerun: 'true'} }
    - { role: dwmstatus }
    - { role: dwmstatus, vars: { act: 'recompile' } }
    - { role: dwmstatus, vars: { rerun: 'true'} }
    - { role: slock }
    - { role: slock, vars: { act: 'recompile' } }
    - { role: slock, vars: { rerun: 'true'} }
    - { role: slstatus }
    - { role: slstatus, vars: { act: 'recompile' } }
    - { role: slstatus, vars: { rerun: 'true'} }
    - { role: st }
    - { role: st, vars: { act: 'recompile' } }
    - { role: st, vars: { rerun: 'true'} }
    - { role: surf }
    - { role: surf, vars: { act: 'recompile' } }
    - { role: surf, vars: { rerun: 'true'} }
