- name: "FreeBSD | Dwm"
  block:
    - name: "FreeBSD | Dwm | Create {{ suckless_common_build_home }}/{{ role_name }}" # noqa: name[template]
      ansible.builtin.file:
        name: "{{ suckless_common_build_home }}/{{ role_name }}"
        state: directory
        mode: "0700"
        owner: "{{ suckless_common_build_user }}"
        group: "{{ suckless_common_build_group }}"

    - name: "FreeBSD | Dwm | Dependencies"
      community.general.pkgng:
        pkg:
          - freetype2
          - git
          - glib
          - libX11
          - libXft
          - libXinerama
          - libxcb
          - ncurses
          - patch
          - sudo
          - ticcutils
          - webkit2-gtk4
        state: present

    - name: "FreeBSD | Dwm | Compile"
      vars:
        suckless_build_name: "{{ role_name }}"
        suckless_build_repo: "{{ dwm_repo }}"
        suckless_build_branch: "{{ dwm_branch }}"
        suckless_build_patches: "{{ dwm_patches }}"
        suckless_build_patch: "{{ dwm_patch }}"
        suckless_build_path: "{{ suckless_common_build_home }}/{{ role_name }}/repo"
        suckless_build_user: "{{ suckless_common_build_user }}"
        suckless_build_group: "{{ suckless_common_build_group }}"
        suckless_build_recompile: "{{ dwm_recompile }}"
      ansible.builtin.include_tasks:
        file: ../../common/tasks/Compile.yml

  rescue:
    - name: "FreeBSD | Dwm | Fail"
      ansible.builtin.debug:
        msg: "Fail"
      changed_when: true
      # notify:
      #   - send failed message
