- name: "FreeBSD | Dwmstatus"
  block:
    - name: "FreeBSD | Dwmstatus | Create {{ suckless_common_build_home }}/{{ role_name }}" # noqa: name[template]
      ansible.builtin.file:
        name: "{{ suckless_common_build_home }}/{{ role_name }}"
        state: directory
        mode: "0700"
        owner: "{{ suckless_common_build_user }}"
        group: "{{ suckless_common_build_group }}"

    - name: "FreeBSD | Dwmstatus | Dependencies"
      vars:
        pkg_state: present
        pkg_names:
          - freetype2
          - git
          - glib
          - libX11
          - libXft
          - libXinerama
          - libxcb
          - ncurses
          - patch
          - sudo
          - ticcutils
          - webkit2-gtk4
      ansible.builtin.include_role:
        name: ruupert.helpers.pkg

    - name: "FreeBSD | Dwmstatus | Compile"
      vars:
        suckless_build_name: "{{ role_name }}"
        suckless_build_repo: "{{ dwmstatus_repo }}"
        suckless_build_branch: "{{ dwmstatus_branch }}"
        suckless_build_patches: "{{ dwmstatus_patches }}"
        suckless_build_patch: "{{ dwmstatus_patch }}"
        suckless_build_path: "{{ suckless_common_build_home }}/{{ role_name }}/repo"
        suckless_build_user: "{{ suckless_common_build_user }}"
        suckless_build_group: "{{ suckless_common_build_group }}"
        suckless_build_recompile: "{{ dwmstatus_recompile }}"
        suckless_build_timezone: "{{ dwmstatus_timezone }}"
      ansible.builtin.include_tasks:
        file: ../../common/tasks/Compile.yml

  rescue:
    - name: "FreeBSD | Dwmstatus | Fail"
      ansible.builtin.debug:
        msg: "Fail"
      changed_when: true
      # notify:
      #   - send failed message
