- name: "Debian | Wmname"
  block:
    - name: "Debian | Wmname | Create {{ suckless_common_build_home }}/{{ role_name }}" # noqa: name[template]
      ansible.builtin.file:
        name: "{{ suckless_common_build_home }}/{{ role_name }}"
        state: directory
        mode: "0700"
        owner: "{{ suckless_common_build_user }}"
        group: "{{ suckless_common_build_group }}"

    - name: "Debian | Wmname | Dependencies"
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - sudo
          - patch
          - git
          - make
          - libx11-6
          - libx11-xcb1
          - libx11-dev
          - libxft-dev
          - libxinerama-dev
          - libgcr-3-dev
          - libwebkit2gtk-4.0-dev
          - gcc
          - acl
          - libglib2.0-dev
        state: present

    - name: "Debian | Wmname | Compile"
      vars:
        suckless_build_name: "{{ role_name }}"
        suckless_build_repo: "{{ wmname_repo }}"
        suckless_build_branch: "{{ wmname_branch }}"
        suckless_build_patches: "{{ wmname_patches }}"
        suckless_build_patch: "{{ wmname_patch }}"
        suckless_build_path: "{{ suckless_common_build_home }}/{{ role_name }}/repo"
        suckless_build_user: "{{ suckless_common_build_user }}"
        suckless_build_group: "{{ suckless_common_build_group }}"
        suckless_build_recompile: "{{ wmname_recompile }}"
      ansible.builtin.include_tasks:
        file: ../../common/tasks/Compile.yml

  rescue:
    - name: "Debian | Wmname | Fail"
      ansible.builtin.debug:
        msg: "Fail"
      changed_when: true
      # notify:
      #   - send failed message
